language: python
python:
- 3.4
install:
- pip install coveralls scrutinizer-ocular
script:
- make ci
- make run
after_success:
- coveralls
- ocular
notifications:
  email:
    on_success: never
    on_failure: always
